title: Simon Schrottner
description: CNCF Ambassador, OpenFeature maintainer, bearded guy from Austria who loves to code.
author:
  name: Simon Schrottner
  email: simon.schrottner@gmail.com

url: https://schrottner.at

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - .markdownlint.yaml
  - .spelling

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
